services:

  osm_database:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    volumes:
      - ./test/osm_database-schema.sql:/docker-entrypoint-initdb.d/osm_database-schema.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: $NITRO_DATABASE_OSM_SYNC_USER
      POSTGRES_PASSWORD: $NITRO_DATABASE_OSM_SYNC_PASSWORD
      POSTGRES_DB: $NITRO_DATABASE_OSM_SYNC_DB
    ports:
      - 5434:5432

  database:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: $NITRO_DATABASE_APP_USER
      POSTGRES_PASSWORD: $NITRO_DATABASE_APP_PASSWORD
      POSTGRES_DB: $NITRO_DATABASE_APP_DB
    ports:
      - 5432:5432

  redis:
    image: redis:8.2-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres-data:
  redis-data:
